module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testTimeout: 600000,
  coverageThreshold: {
    global: {
      branches: 50,
      functions: 90,
      lines: 90,
      statemants: 50,
    },
  },
  modulePaths: ["src"],
  moduleFileExtensions:['ts','tsx','js','jsx','json','node'],
  collectCoverageFrom: [
    '**/*.resolver.ts',
    '**/modules/**/*.ts',
    '!**/*.entity.ts',
    '!**/*.types.ts',
    '!**/test/**',
    '!**/node_modules/**',
    '!index.ts',
    '!**/vendor/**',
  ],
  moduleDirectories: [
    ".",
    "src",
    "src/util",
    "src/config",
    "src/entities",
    "src/interfaces",
    "src/middlewares",
    "src/modules",
    "src/services",
    "src/test",
    "src/utils",
    "node_modules"
  ],
  moduleNameMapper: {
    '^@api(.*)$': '<rootDir>/src/api$1',
    '^@config(.*)$': '<rootDir>/src/config$1',
    '^@modules(.*)$': '<rootDir>/src/modules$1',
    '^@entities(.*)$': '<rootDir>/src/entities$1',
    '^@utils(.*)$': '<rootDir>/src/utils$1',
    '^@middlewares(.*)$': '<rootDir>/src/middlewares$1',
    '^@test(.*)$': '<rootDir>/src/test$1',
    '^@interfaces(.*)$': '<rootDir>/src/interfaces$1',
    '^@services(.*)$': '<rootDir>/src/services$1',
  },
};
